### PR TITLE
Photo Change

### PR DESCRIPTION
**Pull request by mbolanmbaleni**
ok

### CODE REVIEW

**Comment by mbolanmbaleni** [comment]
try again

**Review by mbolanmbaleni — COMMENTED** [review]
ok

**Review by EnAH7pbh — APPROVED** [review]
ok

**Review by EnAH7pbh — APPROVED** [review]

**Review by EnAH7pbh — APPROVED** [review]
ok view

**Review by mbolanmbaleni — COMMENTED** [review]
hhh

**Review by EnAH7pbh — APPROVED** [review]

**Review by EnAH7pbh — CHANGES_REQUESTED** [review]
change

**Review by EnAH7pbh — APPROVED** [review]
aprove

**Review by EnAH7pbh — APPROVED** [review]
approve

**Comment by EnAH7pbh** [comment]
aprove pls

**Review by EnAH7pbh — CHANGES_REQUESTED** [review]
pls change photos

**Review by mbolanmbaleni — COMMENTED** [review]
ok

**Review by EnAH7pbh — APPROVED** [review]
accept

**Pull request closed without merging**
